# -*- coding: utf-8 -*-
"""临时工具：为 batch_npc_avatars.json 生成英文水彩风提示词（结合原著服装/年龄）"""
import json
import os

PREFIX = "Watercolor painting style, half-body portrait of a Wuxia character, "
SUFFIX = ", ancient Chinese martial arts atmosphere, soft watercolor washes, delicate brush strokes, white background"

# 手工编写的英文描述映射：name -> 年龄+身份+服装+性格（英文，避免内容策略敏感词）
DATA = {
    "圆性（袁紫衣）": "a young Buddhist nun in her early twenties, Emei Sect nun formerly known as Yuan Ziyi, wearing a plain bluish-grey robe with a white hood, calm and reserved",
    "徐铮": "a hot-tempered young man in his early thirties, apprentice of the Flying Horse Escort Agency, wearing a dark grey cloth tunic with tied sleeves, impulsive and jealous",
    "马行空": "a seasoned escort master in his fifties, chief of the Flying Horse Escort Agency, wearing a brown brocade robe over a cloth tunic, steady and stern",
    "何思豪": "a foppish young imperial guard in his twenties, wearing a blue-feathered court guard uniform with a round hat, smug and lecherous",
    "福公子": "a handsome young nobleman in his early twenties, son of a high official, wearing an ornate cream-and-gold brocade robe, charming and flirtatious",
    "福康安之母": "an imperious elderly noblewoman in her sixties, wife of a Manchu minister and mother of the imperial favorite, wearing an embroidered satin gown with ornate headdress, cold and proud",
    "凤天南": "a fierce middle-aged martial arts master in his fifties, chief of the Five Tigers Gate, wearing a dark cloth shirt with a tiger-patterned vest, cunning and ruthless in demeanor",
    "凤一鸣": "a courteous young man in his early twenties, son of Feng Tiannan, wearing a clean blue cloth robe, polite but scheming",
    "凤七": "a shrewd middle-aged innkeeper in his forties, manager of the Heroes Tavern, wearing a plain grey robe, sly and obsequious",
    "锺阿四": "an honest middle-aged vegetable farmer in his thirties, wearing a simple linen tunic and straw sandals, kind and stubborn",
    "锺四嫂": "a sturdy peasant woman in her thirties, wife of a vegetable farmer, wearing a coarse cloth jacket and skirt, loving and fierce",
    "锺小二": "a brave ten-year-old farm boy, eldest son of a vegetable farmer, wearing a patched cotton tunic, innocent and defiant",
    "锺小三": "a small innocent six-year-old farm boy, youngest son of a vegetable farmer, wearing a little cloth shirt, naive and trusting",
    "陈禹": "a sly middle-aged martial artist in his forties, an apostate of the Taiji School, wearing a dark silk robe, cunning and cowardly",
    "孙刚峯": "a righteous but stern master in his fifties, chief of the Guangping Taiji School, wearing a blue cloth robe, dignified and loyal",
    "吕小妹": "a resolute teenage girl around fifteen, daughter of a slain martial artist, wearing a simple blue cotton dress, brave and determined",
    "古般若": "a proud young martial artist in his early twenties, a promising disciple of Shaolin Temple, wearing a grey monk-style tunic, youthful and spirited",
    "殷仲翔": "an irritable middle-aged martial artist in his forties, a master of the Tianlong School, wearing a brown cloth tunic, easily angered",
    "王剑英": "an arrogant middle-aged martial artist in his forties, son of the Bagua Gate master, wearing a dark brocade tunic, proud and opportunistic",
    "王剑杰": "a blunt middle-aged martial artist in his forties, younger son of the Bagua Gate master, wearing a grey cloth tunic, hot-tempered and protective",
    "张总管": "a fussy middle-aged steward in his forties, personal servant of the young nobleman, wearing a neat plain gown, restless and anxious",
    "刘鹤真": "an eccentric elder in his fifties, senior of the Weituo School, wearing a faded grey robe, with weathered features and a stubborn air",
    "仲萍": "a devoted middle-aged woman in her forties, wife of an old martial artist, wearing a plain cotton gown, faithful and gentle",
    "张飞雄": "a timid young disciple of the Tianlong School in his thirties, wearing a dark cloth tunic, sly and fearful",
    "孙伏虎": "a steady young martial artist in his thirties, senior disciple of the Weituo School, wearing a plain blue tunic, composed and reliable",
    "尉迟连": "a sharp-eyed young martial artist in his thirties, second disciple of the Weituo School, wearing a dark tunic, clever and wary",
    "杨宾": "a hot-blooded young martial artist in his thirties, third disciple of the Weituo School, wearing a rough cloth tunic, quick-tempered",
    "蓝秦": "a cautious middle-aged swordsman in his forties, chief of the Eight Immortals Sword School, wearing a green scholar's robe, careful and experienced",
    "曹猛": "a capable imperial guard in his thirties, wearing the blue official uniform of a palace guard, sharp and resourceful",
    "崔百胜": "a capable imperial guard in his thirties, wearing the blue official uniform of a palace guard, sharp and cunning",
    "易吉": "a superstitious middle-aged martial arts master in his forties, chief of the Nine Dragons School, wearing a plain grey robe, irritable and moody",
    "钟兆文": "a burly and tough middle-aged man in his forties, eldest of the three Zhong brothers of Hubei, wearing a short coarse tunic, sturdy and loyal",
    "钟兆英": "a sturdy middle-aged man in his forties, second of the three Zhong brothers, wearing a dark cloth tunic, shrewd and steady",
    "钟兆能": "a burly middle-aged man in his thirties, youngest of the three Zhong brothers, wearing a coarse tunic, tough and alert",
    "慕容景岳": "a gaunt and sinister middle-aged man in his forties, senior disciple of the Poison King, wearing a dark grey robe, brooding and malicious",
    "姜铁山": "a rough and hearty middle-aged man in his forties, second disciple of the Poison King, wearing a plain cloth tunic, sturdy and family-loving",
    "薛鹊": "a hunched middle-aged woman in her forties, third disciple of the Poison King, wearing a dark cloth gown, gentle-looking yet venomous",
    "姜小铁": "a reckless teenage boy in his late teens, son of Jiang Tieshan, wearing a coarse cloth tunic, impulsive and headstrong",
    "王铁匠": "a sturdy blacksmith in his forties, wearing a sleeveless leather apron over a rough shirt, honest and grateful",
    "田青文": "a sharp teenage girl around seventeen, daughter of Tian Guinong, wearing a neat green cloth dress, clever and devoted to her father",
    "秦耐之": "a steady middle-aged martial arts master in his forties, chief of the Baji Boxing School, wearing a dark escort tunic, composed and grateful",
    "周铁鹪": "a robust middle-aged military officer in his forties, senior disciple of the Eagle Claw School, wearing a dark official military uniform, broad-shouldered and shrewd",
    "曾铁鸥": "an easy-going middle-aged military officer in his forties, second disciple of the Eagle Claw School, wearing a dark official military uniform, dashing and loyal",
    "汪铁鹗": "a blunt young military officer in his thirties, disciple of the Eagle Claw School, wearing a plain military uniform, outspoken and eager",
    "褚姓老者": "a rough-cut elderly bandit in his fifties, a steppe outlaw from the north, wearing a heavy sheepskin coat, short-tempered",
    "上官姓兄弟": "a wiry middle-aged bandit in his forties, a steppe outlaw from the north, wearing a leather tunic, sly and ruthless",
    "聂钺": "a sword-loving military officer in his thirties, wearing a dark official uniform with a longsword at his waist, upright and respectful",
    "姬晓峯": "a bold young martial artist in his thirties, disciple of the Hua Boxing School, wearing a dark cloth tunic, direct and loyal",
    "蔡威": "a pliable young martial artist in his late twenties, member of the Hua Boxing School, wearing a grey tunic, submissive and treacherous",
    "蔡姓老者": "a witty elderly martial arts master in his fifties, senior of the Hua Boxing School, wearing a blue cloth robe, humorous and sharp-eyed",
    "高云": "a lively young female martial artist in her early twenties, disciple of the Hua Boxing School, wearing a trim blue tunic, spirited and capable",
    "张复龙": "a diligent young martial artist in his early twenties, disciple of the Hua Boxing School, wearing a plain cloth tunic, earnest and studious",
    "褚轰": "a reckless young martial artist in his thirties, disciple of the Thunder School of the North, wearing a coarse tunic, brash and impulsive",
    "德莽夫": "a rough and brutish man in his thirties, a hired thug, wearing a patched cloth tunic, coarse and overbearing",
    "武官头领": "a sinister military officer in his forties, an official under Fu Kang'an, wearing a dark official uniform, cunning and cold",
    "和嘉公主": "an elegant young princess in her late twenties, fourth daughter of the Qianlong Emperor, wearing an ornate Manchu court gown, gracious and talkative",
    "海兰氏": "a composed noblewoman in her thirties, wife of the imperial favorite Fu Kang'an, wearing an embroidered satin gown, restrained yet proud",
    "福长安之妻": "a gentle noblewoman in her thirties, wife of a high Manchu official, wearing a modest embroidered gown, mild and proper",
    "张九": "a rough guard in his thirties, an escort of the Fu mansion, wearing a plain cloth tunic, coarse and brutish",
    "任通武": "a greedy left-camp guard in his thirties, wearing a grey guard uniform, fond of wine and timid",
    "全管家": "an attentive middle-aged steward in his forties, butler sent by Zhou Tiejiu, wearing a neat dark gown, deferential and diligent",
    "黑大汉": "a big swarthy man in his thirties, a house seller, wearing a rough cloth tunic, blunt and direct",
    "马春花之子": "a chubby baby boy in swaddling clothes, infant son of Ma Chunhua and Fu Kang'an, sleeping peacefully",
    "老妇人": "a frail elderly woman in her sixties, a sick woman resting in a stone hut, wearing a plain grey gown, frightened and feeble",
    "大智禅师": "a venerable old abbot of Shaolin in his seventies, with a shaven head and long white eyebrows, wearing a golden-brown kasaya robe, solemn and kind",
    "无青子": "an unassuming elderly Taoist priest in his sixties, abbot of the Wudang Taihe Palace, wearing a grey Taoist robe, humble yet deep",
    "陆菲青": "a gentle elderly Taoist master in his eighties, a famed Wudang elder, wearing a blue-grey Taoist robe with white hair, serene and skillful",
    "汤沛": "an elegant middle-aged high martial artist in his fifties, chief of the Three Talents Sword School, wearing a fine brocade robe, outwardly gracious but treacherous",
    "海兰弼": "a sturdy middle-aged Manchu officer in his forties, chief of the Black Dragon School and a banner officer, wearing a dark banner-uniform, bold and quick-tempered",
    "黄希节": "a powerful middle-aged martial arts master in his forties, chief of the Two Fists School, wearing a dark cloth tunic, burly and strong",
    "欧阳公政": "a flamboyant middle-aged martial arts master in his forties, chief of the Yanqing Boxing School, wearing a dark tunic, reckless and vain",
    "西灵道人": "a smiling elderly Taoist swordsman in his sixties, chief of the Kunlun Saber School, wearing a grey Taoist robe, wise and retiring",
    "文醉翁": "a disheveled middle-aged martial arts master in his fifties, chief of the Drunken Eight Immortals School, wearing a rumpled robe, boastful and timid",
    "周隆": "a tenacious middle-aged escort master in his forties, chief of the Vajra Fist School and head of an escort agency, wearing a dark escort tunic, tough and honorable",
    "齐伯涛": "a coarse young martial artist in his twenties, disciple of the Duck-Form School, wearing a plain cloth tunic, rough-mannered",
    "陈高波": "a coarse young martial artist in his twenties, disciple of the Duck-Form School, wearing a plain cloth tunic, rough-mannered",
    "宗雄": "an explosive middle-aged martial arts master in his forties, chief of the Earth Hall Fist School, wearing a dark tunic, mighty and short-tempered",
    "桑飞虹": "a lively young woman in her twenties, chief of the Five Lakes Gate, wearing a neat blue riding outfit, curious and brave",
    "倪不大": "a strange middle-aged man in his forties, one of the conjoined twin chiefs of the Gemini Gate, wearing a wide grey tunic, uncanny and silent",
    "倪不小": "a strange middle-aged man in his forties, the other of the conjoined twin chiefs of the Gemini Gate, wearing a wide grey tunic, uncanny and silent",
    "哈赤": "a burly Mongolian wrestling master in his forties, chief of the Zhongzha Gate, wearing a fur-trimmed leather robe, honest and hot-tempered",
    "上官铁生": "a sinister middle-aged martial artist in his forties, chief of the Xuanzhi Gate, wearing a grey robe and holding a long tobacco pipe, sly and venomous",
    "青年书生": "an elegant young scholar in his twenties, secretly a member of the Red Flower Society, wearing a plain white scholar's robe, handsome and witty",
    "常赫志": "a cold-faced martial master in his forties, one of the Twin Heroes of West Sichuan of the Red Flower Society, wearing a dark tunic, stern and skilled",
    "常伯志": "a cold-faced martial master in his forties, the other of the Twin Heroes of West Sichuan of the Red Flower Society, wearing a dark tunic, stern and skilled",
    "郭玉堂": "a knowledgeable middle-aged martial arts master in his forties, chief of the Celestial Fist School, wearing a brown scholar's robe, knowledgeable and wary",
    "童怀道": "a blunt martial master in his forties, a meteor hammer expert from Taiyuan, wearing a plain tunic with a rope belt, outspoken and fierce",
    "曹云奇": "a devoted young swordsman in his twenties, senior disciple of Tian Guinong, wearing a dark tunic and carrying a sword, loyal and earnest",
    "李廷豹": "a rough middle-aged escort master in his forties, chief disciple of the Wutai School and head escort, wearing a dark escort tunic, brash and honorable",
    "石万嗔": "an old venomous master in his sixties, junior brother of the Poison King, wearing a dark grey robe, withered and sinister",
    "柯子容": "a proud middle-aged martial artist in his forties, chief of the Seven Green School of Lanzhou, wearing a dark tunic, self-important and combative",
    "木文察": "a bold Manchu general in his forties, a fierce officer under Fu Kang'an, wearing a metal lamellar armor over military robes, valiant and shrewd",
    "安提督": "a portly high-ranking military governor in his forties, an official under Fu Kang'an, wearing an embroidered court robe, obsequious and self-important",
    "刘之余": "a timid middle-aged palace eunuch in his forties, serving in the imperial court, wearing a plain grey palace robe, nervous and quiet",
    "石双英": "a fierce young martial artist in his thirties, a veteran of the Red Flower Society known as the Ghost Facer, wearing a dark tunic, bold and grim",
    "无尘道人": "a vigorous old Taoist in his sixties, second chief of the Red Flower Society with a single arm, wearing a grey Taoist robe with a sword, proud and sword-brilliant",
    "德布": "a mighty Manchu guard captain in his forties, the strongest imperial bodyguard, wearing a dark court guard uniform, brave and arrogant",
    "徐天宏": "a clever young strategist in his thirties, seventh chief of the Red Flower Society known as the Martial Zhuge, wearing a scholar's robe over a tunic, sharp-witted and calm",
    "心砚": "a quick young page boy in his late teens, private attendant of the Red Flower Society's chief, wearing a simple grey tunic, nimble and clever",
    "苗夫人": "a beautiful middle-aged woman in her forties, former wife of Miao Renfeng, wearing an elegant Chinese silk gown, proud and mysterious",
    "司徒雷": "a cautious middle-aged swordsman in his forties, a warrior in Fu Kang'an's mansion, wearing a dark tunic, wary and evasive",
    "谢不挡": "a cautious middle-aged swordsman in his forties, a warrior in Fu Kang'an's mansion, wearing a dark tunic, wary and evasive",
    "张宁": "a shrewd young warrior in his thirties, a guard in Fu Kang'an's mansion, wearing a dark tunic, crafty and smooth",
    "丁文沛": "a shrewd young warrior in his thirties, a guard in Fu Kang'an's mansion, wearing a dark tunic, crafty and smooth",
    "丁文深": "a shrewd young warrior in his thirties, a guard in Fu Kang'an's mansion, wearing a dark tunic, crafty and smooth",
    "陈敬夫": "a self-regarding older warrior in his forties, a guard in Fu Kang'an's mansion who claims to be a veteran, wearing a dark tunic, proud and conceited",
    "黄樵": "a swift middle-aged warrior in his forties, a guard in Fu Kang'an's mansion skilled in grappling, wearing a dark tunic, agile and strong",
    "伍公权": "a steady middle-aged warrior in his forties, a guard in Fu Kang'an's mansion, wearing a dark tunic, solid and calm",
    "高一力": "a huge young warrior in his twenties, a tall strong guard in Fu Kang'an's mansion, wearing a dark tunic, strong and simple",
    "东方": "a slick middle-aged warrior in his forties, a guard in Fu Kang'an's mansion, wearing a dark tunic, smooth and sly",
    "邝宝官": "a crafty middle-aged gambling den keeper in his forties, wearing a dark grey robe, sly and greedy",
    "蛇皮张": "a timid middle-aged escort fighter in his forties, a guard at a pawnshop, wearing a brown tunic, fearful and fawning",
    "俞朝奉": "a sharp-voiced middle-aged pawnshop appraiser in his forties, wearing a dark robe, sarcastic and stingy",
    "大掌柜": "a smooth middle-aged shopkeeper in his forties, head manager of a pawnshop, wearing a dark scholar robe, shrewd and worldly",
    "肥厨子": "a plump middle-aged cook in his forties, chef of a tavern, wearing a white apron over a plain tunic, honest and good-natured",
    "尤七": "a petty middle-aged tavern keeper in his forties, wearing a grey tunic, snobbish and calculating",
    "蒋调侯": "a cunning imperial guard in his forties, wearing a dark court guard uniform, sly and treacherous",
    "补锅匠": "a coarse middle-aged tinker in his forties, disciple of the Zhong brothers of Hubei, wearing a patched tunic, rough and arrogant",
    "脚夫": "a rugged young porter in his thirties, one of a gang of bandits, wearing rough laborer clothes, fierce and reckless",
    "车夫": "a lustful middle-aged cart driver in his forties, one of a gang of bandits, wearing rough laborer clothes, lecherous and coarse",
    "店伴": "a crafty young shop assistant in his twenties, actually a disguised bandit, wearing a plain grey tunic, cunning and sly",
    "南仁通": "an arrogant middle-aged official in his forties, father of Nan Lan and a reserve court official, wearing a dated official robe, proud and greedy",
    "聂姓大盗": "a proud middle-aged swordsman in his forties, a Zhejiang swordsman in Fu Kang'an's service, wearing a dark tunic with a longsword, proud and sword-devoted",
    "中年妇人": "a composed middle-aged woman in her forties, secretly the Poison Iris Cheng Lingsu in disguise, wearing a plain farmer woman's dress, calm and crafty",
    "石先生": "a sinewy old man in his sixties, claiming to be the Poison King, actually Shi Wanqin, wearing a dark grey worn robe, sly and venomous",
    "平四": "a faithful one-armed man in his forties, servant and foster father of Hu Fei, wearing a patched cloth tunic, loyal and enduring",
    "锺兆英": "a steady middle-aged man in his forties, eldest of the Zhong brothers, wearing a dark coarse tunic, level-headed and trustworthy",
    "锺兆文": "a rough middle-aged man in his forties, second of the Zhong brothers, wearing a dark coarse tunic, quick-tempered yet chivalrous",
    "锺兆能": "a sharp middle-aged man in his late thirties, youngest of the Zhong brothers, wearing a dark coarse tunic, alert and witty",
    "福康安之母（老夫人）": "an imperious elderly noblewoman in her sixties, mother of the imperial favorite Fu Kang'an, wearing an ornate satin gown with a formal headdress, cold and ruthless",
    "德莽夫（姓德的莽夫）": "a rough and brutish man in his thirties, a hired thug, wearing a patched cloth tunic, coarse and overbearing",
    "武官头领（下毒盒者）": "a sinister military officer in his forties, an official under Fu Kang'an, wearing a dark official uniform, cunning and cold",
    "苗夫人（南兰）": "a beautiful middle-aged woman in her forties, the former wife of Miao Renfeng who remarried Tian Guinong, wearing an elegant silk gown, proud and mysterious",
    "马春花之子（二人）": "two chubby baby boys in swaddling clothes, twin infants of Ma Chunhua and Fu Kang'an, peaceful and rosy",
    "黑大汉（姓德）": "a big swarthy man in his thirties, a house seller, wearing a rough cloth tunic, blunt and direct",
    "东方（姓东方，名不详）": "a slick middle-aged warrior in his forties, a guard in Fu Kang'an's mansion, wearing a dark tunic, smooth and sly",
    "中年婦人": "a composed middle-aged woman in her forties, secretly the Poison Iris Cheng Lingsu in disguise, wearing a plain farmer woman's dress, calm and crafty",
    "书生": "an elegant young scholar in his twenties, secretly a member of the Red Flower Society, wearing a plain white scholar's robe, handsome and clever with light kung fu",
    "平斐（胡斐）": "a brave teenage boy of about seventeen, son of the slain hero Hu Yidao, in disguise as a farm lad, wearing a simple cloth tunic, bright-eyed and courageous",
    "护院老周（铁臂周）": "an honest middle-aged house guard in his forties, personal martial arts instructor of the protagonist's family, wearing a plain tunic, sturdy and loyal",
    "李公福": "a kindly elderly landowner in his sixties, master of the Li household in Baoding and father of the player character, wearing a dark blue broadcloth robe, dignified and warm",
    "灵儿": "a cheerful young maid in her late teens, personal maid of the Li household, wearing a short green jacket and skirt, lively and innocent",
    "赵镖头": "a hearty middle-aged escort in his forties, an escort master of the Flying Horse Escort Agency in Cangzhou, wearing a dark escort tunic, bold and honorable",
    "于万亭": "a righteous old martial hero in his sixties, former chief of the Red Flower Society, wearing a dark plain robe, resolute and devoted",
    "木卓伦": "a stalwart old chieftain in his sixties, leader of the Muslim Uighur tribe and father of Huo Qingtong, wearing a white cloak and turban, generous and unyielding",
    "周绮": "a spirited young woman in her early twenties, daughter of Zhou Zhongying nicknamed the Pretty Li Kui, wearing a neat blue jacket and skirt, fiery and kind-hearted, holding a saber",
    "周英杰": "a cute young boy of about thirteen, youngest son of Zhou Zhongying, wearing a small blue tunic, playful and innocent",
    "马真": "a benign elderly Taoist in his sixties, chief of the Wudang School and senior brother of Zhang Zhaozhong, wearing a grey Taoist robe, upright and soft-hearted",
    "白振": "a grim old imperial bodyguard chief in his sixties, head of the imperial guards, wearing a dark court guard uniform, loyal and ruthless",
    "瑞大林": "a sinister middle-aged imperial guard in his forties, wearing a dark court guard uniform, ruthless and cruel",
    "褚圆": "a fierce middle-aged imperial guard in his forties, a red-robed sword expert of the palace guards, wearing a dark red tunic, combative and aggressive",
    "龙骏": "a sly middle-aged hidden-weapon expert in his forties, an imperial agent, wearing a dark tunic with a small knife pouch, cunning and treacherous",
    "言伯乾": "a sinister middle-aged hidden-weapon expert in his forties, an imperial agent, wearing a dark tunic, cunning and venomous",
    "蒋四根": "a huge sturdy young man in his thirties, tenth chief of the Red Flower Society, wearing a dark cloth tunic and wielding an iron oar, simple and mighty",
    "杨成协": "a burly martial man in his thirties, eighth chief of the Red Flower Society, wearing a dark tunic, hearty and straight",
    "卫春华": "an agile young martial artist in his thirties, ninth chief of the Red Flower Society, wearing a light tunic and carrying twin hooks, nimble and fearless",
    "章进": "a hunchbacked sturdy man in his mid-thirties, a chief of the Red Flower Society, wearing a loose grey tunic, irritable but fiercely loyal",
    "蒋天寿": "a steady middle-aged man in his forties, sixth chief of the Red Flower Society, wearing a dark plain tunic, composed and experienced",
    "孟健雄": "an honest middle-aged steward in his forties, butler of the Iron Gall Bladder Manor, wearing a plain grey robe, loyal and plain",
    "安健刚": "a rough straight-forward middle-aged martial instructor in his forties, teacher of the Iron Gall Bladder Manor, wearing a plain tunic, sturdy and plain-spoken",
    "万庆澜": "a sneaky middle-aged man in his forties, a Qing spy, wearing an ordinary dark robe, sly and scheming",
    "滕一雷": "a ferocious middle-aged bandit lord in his forties, leader of the northeastern outlaws, wearing a fur-trimmed leather tunic and carrying his thunder shield, fierce and overbearing",
    "顾金标": "a sinister middle-aged outlaw in his forties, a notorious hidden-weapon master of the northeast, wearing a fur-trimmed tunic, cunning and cruel",
    "哈合台": "a burly honest Mongolian warrior in his forties, companion of the northeastern outlaws, wearing a fur coat and boots, plain and brave",
    "焦文期": "a worldly middle-aged escort in his forties, a skilled mantra-arm boxer, wearing a dark escort tunic, smooth and worldly",
    "韩文冲": "a timid middle-aged escort in his forties, an escort master, wearing a dark escort tunic, cautious and careful",
    "王维扬": "a dignified elderly martial arts master in his seventies, chief of the Bagua Gate and head of a major escort agency, wearing a dark brown brocade robe, stately and virtuous",
    "阿凡提": "a witty old scholar of the Muslim lands in his sixties, a wise man of Xinjiang, wearing a white robe and a small round fur hat with a goatee, humorous and quick-witted",
    "霍阿伊": "a brave young warrior in his early thirties, son of the Uighur chieftain and brother of Huo Qingtong, wearing a white robe with a turban, bold and straightforward",
    "闫世魁": "a stubborn middle-aged Qing general in his forties, commander in charge of the campaign against the Uighurs, wearing metal armor over official robes, rigid and headstrong",
    "章虚": "a learned elderly Shaolin monk in his sixties, a senior monk of the temple, wearing a grey kasaya robe, compassionate and wise",
    "彭三春": "a timeserving middle-aged martial artist in his forties, a wandering martial arts master, wearing a dark tunic, obsequious and worldly",
    "沈德潜": "a refined elderly court scholar in his sixties, a favored official of the Qianlong Emperor, wearing a plain dark court robe, polished and flattering",
    "卓天雄": "a grim elderly imperial guard expert in his sixties, a senior martial master of the palace, wearing a dark tunic, ruthless and arrogant",
    "周威信": "a worried middle-aged escort master in his forties, chief of the Weixin Escort Agency nicknamed Iron Whip, wearing a dark escort tunic, cautious and worldly",
    "逍遥子": "a boastful middle-aged wanderer in his forties, leader of the Four Heroes of Taiyue, wearing a loose grey robe, bombastic and comical",
    "天池怪侠": "a mysterious old master in his sixties, a reclusive martial arts sage of the Tianshan mountains, wearing a rough grey robe with long white hair and beard, eccentric and mighty",
    "铁镜": "a dignified middle-aged Shaolin monk in his forties, abbot of the Dharma Hall of Shaolin, wearing a grey kasaya robe, compassionate and just",
    "常长风": "a proud funny middle-aged man in his forties, second of the Four Heroes of Taiyue, wearing a loose cloth tunic, boastful and comical",
    "花剑影": "a proud funny middle-aged man in his forties, third of the Four Heroes of Taiyue, wearing a loose cloth tunic, boastful and comical",
    "盖一鸣": "a proud funny middle-aged man in his forties, fourth of the Four Heroes of Taiyue, wearing a loose cloth tunic, boastful and comical",
    "周老茶": "a worldly middle-aged tea shop owner in his forties, an old friend of Ma Xingkong with knowledge of the jianghu, wearing a simple grey tunic, shrewd and friendly",
    "言达平": "a scheming middle-aged man in his forties, second disciple of the betrayed master Mei Niansheng, wearing worn tattered clothes as a disguised beggar, cunning and patient",
    "凌退思": "a greedy middle-aged prefect in his forties, magistrate of Jingzhou, wearing a dark official robe, avaricious and cruel",
    "梅念笙": "a righteous elderly martial arts master in his sixties, keeper of the Liancheng secret manual, wearing a plain grey robe, upright and perceptive",
    "血刀老祖": "a withered elderly Tibetan monk in his sixties, chief of the Blood Knife Sect, with a shaven head and fiery eyes, wearing a loose red monk robe, fierce and sly",
    "水岱": "a righteous middle-aged swordsman in his forties, one of the Southern Four Heroes nicknamed Cold Moon Sword, wearing a white robe and carrying a sword, upright and fierce",
    "花铁干": "a stern middle-aged martial artist in his forties, one of the Southern Four Heroes nicknamed Twin Spears, wearing a dark tunic with twin spears, outwardly righteous but cowardly within",
    "陆天抒": "a bold middle-aged swordsman in his forties, one of the Southern Four Heroes, wearing a dark tunic with a sword, hearty and upright",
    "刘乘风": "a calm middle-aged swordsman in his forties, one of the Southern Four Heroes, wearing a plain tunic with a sword, composed and reserved",
    "宝象": "a burly foolish young monk in his twenties, a disciple of the Blood Knife Sect, wearing a loose red monk robe, crude and dull",
    "汪啸风": "a handsome young swordsman in his early twenties, one of the Bell Sword Duo and cousin of Shui Sheng, wearing a white tunic with a sword, upright but jealous",
    "卜垣": "a sly young martial artist in his twenties, disciple of Wan Zhenshan, wearing a plain tunic, smooth and crafty",
    "吕通": "a rough middle-aged bandit in his forties, a wandering outlaw, wearing a dark tunic with a sabre, coarse and fierce",
    "空心菜": "a sweet innocent little girl of about four, daughter of Qi Fang and a deceased hero, wearing a small pink cloth dress, cute and innocent",
    "吴六奇": "a heroic middle-aged outlaw general in his forties, Red Banner elder of the Heaven & Earth Society, wearing a dark versatile tunic, loyal and righteous",
    "铁雄": "a vicious middle-aged chief in his forties, head of Iron Gate Stronghold, wearing a dark iron-studded tunic, greedy and ruthless",
    "阮士中": "a steady middle-aged martial artist in his forties, disciple of the Northern Tianlong School, wearing a plain dark tunic, calm and loyal",
    "殷吉": "a hearty middle-aged martial artist in his forties, chief of the Southern Tianlong School, wearing a dark tunic, forthright and upright",
    "熊元献": "a rough middle-aged martial artist in his forties, a northeastern hero wielding a chain spear, wearing a fur-trimmed tunic, coarse and frank",
    "郑三娘": "a tough middle-aged female bandit in her forties, a northeastern outlaw wielding twin blades, wearing a fur-trimmed tunic, fierce and bold",
    "陶子安": "a sharp young martial artist in his twenties, disciple of the Tianlong School and fiance of Tian Qingwen, wearing a plain tunic, clever and capable",
    "刘元鹤": "a sly middle-aged imperial guard in his forties, sent to track a hidden treasure, wearing a dark court guard uniform, cunning and treacherous",
    "焦蛟": "a fierce burly bandit chief in his forties, leader of the water stronghold on the Han River nicknamed Wave-Dragon, wearing a coarse tunic, ruthless and bold",
}

def main():
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "batch_npc_avatars.json")
    with open(path, "r", encoding="utf-8") as f:
        items = json.load(f)
    missing = [it["name"] for it in items if it["name"] not in DATA]
    if missing:
        print("缺少映射:", len(missing), missing)
        return
    for it in items:
        it["prompt"] = PREFIX + DATA[it["name"]] + SUFFIX
    with open(path, "w", encoding="utf-8") as f:
        json.dump(items, f, ensure_ascii=False, indent=2)
    print("完成，共", len(items), "条")

if __name__ == "__main__":
    main()